-- This is an example SQLX file to help you learn the basics of Dataform.
-- Visit https://cloud.google.com/dataform/docs/sql-workflows for more information on how to configure your SQL workflow.

-- You can delete this file, then commit and push your changes to your repository when you are ready.

-- Config blocks allow you to configure, document, and test your data assets.
config {
  type: "table", // Creates a table in BigQuery. 
  columns: {
    test: "A description for the fisrt table", // Column descriptions are pushed to BigQuery.
  }
}

-- The rest of a SQLX file contains your SELECT statement used to create the table.

SELECT 1 as number 
union all
select 5 as number
union all
select 10 as number
